ip_node_master: 10.113.198.50

docker_dependencies:
  - yum-utils 
  - device-mapper-persistent-data
  - lvm2
  - epel-release

kubernetes_dependencies:
  - kubelet
  - kubeadm
  - kubectl

token_file: join_token

services:
  - docker
  - kubelet

ports:
  - "6443/tcp"
  - "10250/tcp"
