ip_node_master: 192.241.140.142

docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - gnupg2
  - python-pip

kubernetes_dependencies:
  - kubelet=1.15.10-00
  - kubeadm=1.15.10-00
  - kubectl=1.15.10-00

token_file: join_token

services:
  - docker
  - kubelet

ports:
  - "6443/tcp"
  - "10250/tcp"
