---
- name: "Instalando dependencias"
  yum:
    update_cache: yes
    # cache_valid_time: "3600"
    name: "{{ item }}"
    state: latest
  with_items: "{{ docker_dependencies }}"
  become: true

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0
  become: yes

- name: Enable Docker Test repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-test'
    option: enabled
    value: 0
  become: yes

- name: "Instalando docker"
  yum:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - docker-ce
    - containerd.io
    - docker-ce-cli
  notify:
    - restart docker

- name: Instalando pip
  package:
    name: python-pip
    state: latest
  become: true

- name: Instalando Docker Modulo pro python
  pip:
    name: docker
  become: true

