---
- name: "Instalando dependencias"
  yum:
    update-cache: yes
    cache_valid_time: "3600"
    name: "{{ item }}"
    state: latest
  with_items: "{{ docker_dependencies }}"
  become: true

- name: "Adicionado GPC key do docker"
  yum_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: "Adicionando yum repository do docker"
  yum_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: true

- name: "Instalando docker"
  yum:
    update-cache: yes
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - docker-ce
    - containerd.io
    - docker-ce-cli
  notify:
    - restart docker

- name: Instalando Docker Modulo pro python
  pip:
    name: docker
  become: true
