---
- name: "Copiando token"
  copy:
    src: /home/juniordev/Documentos/oddin-suite/ansible-k8s/{{ token_file }}
    dest: /home/join_token
  become: true

- name: "Adicionado maquina ao no master"
  shell: |
    kubeadm reset -f
    cat /home/join_token | tail -2 > out.sh
    sh out.sh
  become: true
